### ISSUE TITLE
Refactor backend into controllers and routes

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Back#139]
To keep routes clean and concise, we should move all functionality into controllers. Additionally, repeated functionality should all be moved into a utils file.

**Comment by aidenszeto** [comment]
@aidenszeto & @dhruvsangamwar: `googleLogin.js`
@teekenzie: `housekeeping.js`
@syd-tan: `signup.js` and `login.js`

**Comment by aidenszeto** [comment]
Routes to refactor:
 - [] `accountVerification.js`
 - [] `adminVerification.js`
 - [] `contact.js`
 - [] `container.js`
 - [] `exports.js`
 - [] `googleLogin.js`
 - [] `housekeeping.js`
 - [] `listing.js`
 - [] `login.js`
 - [] `payment.js`
 - [] `payout.js`
 - [] `photos.js`
 - [] `ping.js`
 - [] `questionnaire.js`
 - [] `reservation.js`
 - [] `reviews.js`
 - [] `roommates.js`
 - [] `signup.js`
 - [] `subscribe.js`
 - [] `user.js`

**Comment by nishantbalaji** [comment]
@aidenszeto i can handle the listing and user routes
