### ISSUE TITLE
Cannot Create a Listing

### ISSUE THREAD

**Issue by nishantbalaji** [staynomad/Nomad-Back#169]
# Background

This error pops up when I try to save the listing I'm creating as a draft
![image](https://user-images.githubusercontent.com/44332326/126838439-a3994e79-0715-4228-9fc4-b036f86eda86.png)

Same error when I submit:
![image](https://user-images.githubusercontent.com/44332326/126838619-84c95c86-79d6-4a03-a8ba-7ef330690d39.png)

# Task

* Fix the route and make it correctly save the draft
* Fix the route and make it correctly submit the listing

# Done When

* Loading spinner doesn't spin indefinitely

**Comment by aidenszeto** [comment]
Looks like this is working for me in staging environment
