### ISSUE TITLE
Listing popularity ranking/scoring

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Back#43]
We want to find a way to rank listings by popularity. Here's a potential approach:
- Add a "popularity" field in the Listing model of type `int` 
- Increment the popularity score for every page visit (can either create a new route to call on listing page mount or add the counter to the `/byId/:id` route)
- Reset this score at the beginning of every week

We could also consider when the listing was last visited, so adding a "lastVisited" field in the Listing model is an option as well.

**Comment by aidenszeto** [comment]
For now we can focus on making the model/route changes. Once those are done let's move onto the frontend.

**Comment by teekenzie** [comment]
ok

**Comment by teekenzie** [comment]
I don't think we should reset the score every week, because then what's going to happen at the start of every week...

**Comment by aidenszeto** [comment]
We could maybe delay the updates to the ordering of the listings on the frontend for a day so its not just random at the start of every week. I'll let you decide how you want to score them though, the comment is just a possible way to do it

**Comment by teekenzie** [comment]
How to record popularity:
Fields need to add: 
readings (or a better name): an array of integers, represents the number of visits in the past 7 days. Each indexes in the array represent the day of the week.
popularity: int
Every night at 12:01, the array indexes that correspond with the current day with be set to 0 and the popularity will be subtracted accordingly (subtract before set to 0). 
Use node-cron to automate this process.('0 0 * * *)'

**Comment by teekenzie** [comment]
create a new route for incrementing, everytime incremented, record something to local storage so we are incrementing unique views and simply refreshing won't update the view count

**Comment by teekenzie** [comment]
Routes created: listings/increment/:listingId
this route increments the view count and also updated the most recent viewed date.
