### ISSUE TITLE
Create GET routes for popularity

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Back#60]
Desired behavior:
 - Return a (sorted?) list of listing objects within the popularity collection
 - Parameter indicating how many listings we want to return, if it is greater than the number of listings in the popularity collection, return the max

**Comment by aidenszeto** [comment]
We can discuss where we want to sort the listings (front or back) in the meeting tomorrow

**Comment by teekenzie** [comment]
sort it in the back, mongoose has a sort function that we could take advantage of. 

Do you want me to do pagination system where I return all or just return how many is requested . 
or both

**Comment by aidenszeto** [comment]
We should have the option to return either a certain number of listings or all of the listings

**Comment by teekenzie** [comment]
aight done
the routes are:
/popularlistings/:numberOfListing
/allPopularityListings

**Comment by aidenszeto** [comment]
Sounds good I'll create a PR for it.
